export const defaultStyles: React.CSSProperties = {
  backgroundPosition: "center",
  objectFit: "cover",
  backgroundRepeat: "no-repeat",
  textAlign: "left",
  opacity: "100%",
};

export const ALIAS_SHARE_KEY = "alias_shared__dir__name";

export const DOCKER_CONTAINER_BASE_FILE_NODE = "/home/browxy";

export type WebEditorButtons =
  | "container"
  | "2Col"
  | "3Col"
  | "grid"
  | "text"
  | "inputText"
  | "inputTextarea"
  | "inputDate"
  | "combobox"
  | "inputNumber"
  | "inputColor"
  | "inputFile"
  | "checkbox"
  | "image"
  | "video"
  | "audio"
  | "button"
  | "link"
  | "downloadLink"
  | "table"
  | "customSourceContent"
  | "json"
  | "formGroup"
  | "email"
  | "whatsapp"
  | "iframe"
  | "emailButton"
  | "whatsappButton"
  | "navbar"
  | "separator"
  | "tabs"
  | "parallax"
  | "gallery"
  | "html"
  | "__body"
  | null;

export const githubVideoAssets = {
  basePath:
    "https://github.com/elPoeta/browxy-assets/raw/refs/heads/main/builder/videos",
  newProject: "builder-01-new-project.webm",
  confProject: "builder-02-conf-project.webm",
  confProjectConnectDb: "builder-03-conf-connectdb.webm",
  confProjectCreateTableDb: "builder-04-conf-dbcreate-table.webm",
  newPage: "builder-05-new-page.webm",
  confContainer: "builder-06-conf-container.webm",
  editPage: "builder-07-edit-page.webm",
  livePage: "builder-08-live-page.webm",
  confDeploy: "builder-09-deploy.webm",
};

export const githubImageAssets = {
  basePath:
    "https://raw.githubusercontent.com/elPoeta/browxy-assets/refs/heads/main/builder/images",
  configProject: "builder-01-config.png",
  configProjectStorage: "builder-02-storage.png",
  configProjectStorageSize: "builder-03-storage.png",
  configProjectStorageUpload: "builder-04-storage.png",
  configProjectStorageFileTree: "builder-05-storage.png",
  configProjectSchedule: "builder-06-schedule.png",
  componentLayouts: "builder-07-component-layouts.png",
  componentNavigation: "builder-08-component-navigation.png",
  componentForms: "builder-09-component-forms.png",
  componentPresentation: "builder-10-component-presentation.png",
  componentInputs: "builder-11-component-inputs.png",
  componentMultimedia: "builder-12-component-multimedia.png",
  componentDatasources: "builder-13-component-datasources.png",
  componentButtons: "builder-14-component-buttons.png",
  componentCustom: "builder-15-component-custom.png",
};
export const githubImageTemplateAssets = {
  basePath:
    "https://raw.githubusercontent.com/elPoeta/browxy-assets/refs/heads/main/templates/images",
  defaultNoImage: "defaultNoImage.png",
};

export const defaultAssetImage =
  "data:image/svg+xml;base64,PHN2ZyBmaWxsPSIjY2ZjZmNmIiB2aWV3Qm94PSIwIDAgMjQgMjQiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgc3Ryb2tlPSIjY2ZjZmNmIj48ZyBzdHJva2Utd2lkdGg9IjAiPjwvZz48ZyAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIj48L2c+PGc+PHBhdGggZD0iTTIyLDNIMkExLDEsMCwwLDAsMSw0VjIwYTEsMSwwLDAsMCwxLDFIMjJhMSwxLDAsMCwwLDEtMVY0QTEsMSwwLDAsMCwyMiwzWk0yMSwxOUgzdi0uNTMxbDUuMDMzLTQuMiwxLjMuOTc3TDguMjkzLDE2LjI5M2ExLDEsMCwwLDAsMS40MTQsMS40MTRsNi4xODUtNi4xODVMMjEsMTguMzMzWm0wLTRMMTYuOCw5LjRhMSwxLDAsMCwwLTEuNTA3LS4xMDdsLTQuNTMsNC41M0w4LjYsMTIuMmExLDEsMCwwLDAtMS4yNC4wMzFMMywxNS44NjVWNUgyMVpNNSw5YTIsMiwwLDEsMSwyLDJBMiwyLDAsMCwxLDUsOVoiPjwvcGF0aD48L2c+PC9zdmc+Cg==";

export const parameterTypes = [
  { id: 1, name: "SingleLineText" },
  { id: 2, name: "MultipleLineText" },
  { id: 3, name: "TextWithFormat" },
  { id: 4, name: "Hidden" },
  { id: 5, name: "SingleOption" },
  { id: 6, name: "MultipleOption" },
  { id: 7, name: "GPSCoordinates" },
  { id: 8, name: "Image" },
  { id: 9, name: "Sound" },
  { id: 10, name: "Video" },
  { id: 11, name: "File" },
  { id: 12, name: "Slider" },
  { id: 13, name: "ColorPicker" },
  { id: 14, name: "Date" },
  { id: 15, name: "Time" },
  { id: 16, name: "DateTime" },
  { id: 17, name: "Password" },
  { id: 18, name: "Number" },
  { id: 19, name: "Route" },
  { id: 20, name: "OutputFileName" },
  { id: 21, name: "Matrix" },
];

export const outputTypes = [
  { id: 1, name: "Text - Single Output" },
  { id: 2, name: "Text - Interactive" },
  { id: 3, name: "Image" },
  { id: 4, name: "Video" },
  { id: 5, name: "Audio" },
  { id: 6, name: "File" },
  { id: 7, name: "Html" },
  { id: 8, name: "Multiple" },
  { id: 9, name: "Json" },
];

export const cssProps = [
  "alignContent",
  "alignItems",
  "alignSelf",
  "alignmentBaseline",
  "animation",
  "animationDelay",
  "animationDirection",
  "animationDuration",
  "animationFillMode",
  "animationIterationCount",
  "animationName",
  "animationPlayState",
  "animationTimingFunction",
  "appearance",
  "aspectRatio",
  "backdropFilter",
  "backfaceVisibility",
  "background",
  "backgroundAttachment",
  "backgroundBlendMode",
  "backgroundClip",
  "backgroundColor",
  "backgroundImage",
  "backgroundOrigin",
  "backgroundPosition",
  "backgroundPositionX",
  "backgroundPositionY",
  "backgroundRepeat",
  "backgroundSize",
  "baselineShift",
  "blockOverflow",
  "blockSize",
  "border",
  "borderBlock",
  "borderBlockColor",
  "borderBlockEnd",
  "borderBlockEndColor",
  "borderBlockEndStyle",
  "borderBlockEndWidth",
  "borderBlockStart",
  "borderBlockStartColor",
  "borderBlockStartStyle",
  "borderBlockStartWidth",
  "borderBlockStyle",
  "borderBlockWidth",
  "borderBottom",
  "borderBottomColor",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderBottomStyle",
  "borderBottomWidth",
  "borderCollapse",
  "borderColor",
  "borderEndEndRadius",
  "borderEndStartRadius",
  "borderImage",
  "borderImageOutset",
  "borderImageRepeat",
  "borderImageSlice",
  "borderImageSource",
  "borderImageWidth",
  "borderInline",
  "borderInlineColor",
  "borderInlineEnd",
  "borderInlineEndColor",
  "borderInlineEndStyle",
  "borderInlineEndWidth",
  "borderInlineStart",
  "borderInlineStartColor",
  "borderInlineStartStyle",
  "borderInlineStartWidth",
  "borderInlineStyle",
  "borderInlineWidth",
  "borderLeft",
  "borderLeftColor",
  "borderLeftStyle",
  "borderLeftWidth",
  "borderRadius",
  "borderRight",
  "borderRightColor",
  "borderRightStyle",
  "borderRightWidth",
  "borderSpacing",
  "borderStartEndRadius",
  "borderStartStartRadius",
  "borderStyle",
  "borderTop",
  "borderTopColor",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderTopStyle",
  "borderTopWidth",
  "borderWidth",
  "bottom",
  "boxAlign",
  "boxDecorationBreak",
  "boxDirection",
  "boxFlex",
  "boxFlexGroup",
  "boxLines",
  "boxOrdinalGroup",
  "boxOrient",
  "boxPack",
  "boxShadow",
  "boxSizing",
  "breakAfter",
  "breakBefore",
  "breakInside",
  "captionSide",
  "caretColor",
  "clear",
  "clip",
  "clipPath",
  "clipRule",
  "color",
  "colorAdjust",
  "colorInterpolation",
  "colorRendering",
  "columnCount",
  "columnFill",
  "columnGap",
  "columnRule",
  "columnRuleColor",
  "columnRuleStyle",
  "columnRuleWidth",
  "columnSpan",
  "columnWidth",
  "columns",
  "contain",
  "content",
  "counterIncrement",
  "counterReset",
  "counterSet",
  "cursor",
  "direction",
  "display",
  "dominantBaseline",
  "emptyCells",
  "fill",
  "fillOpacity",
  "fillRule",
  "filter",
  "flex",
  "flexBasis",
  "flexDirection",
  "flexFlow",
  "flexGrow",
  "flexShrink",
  "flexWrap",
  "float",
  "floodColor",
  "floodOpacity",
  "font",
  "fontFamily",
  "fontFeatureSettings",
  "fontKerning",
  "fontLanguageOverride",
  "fontOpticalSizing",
  "fontSize",
  "fontSizeAdjust",
  "fontStretch",
  "fontStyle",
  "fontSynthesis",
  "fontVariant",
  "fontVariantAlternates",
  "fontVariantCaps",
  "fontVariantEastAsian",
  "fontVariantLigatures",
  "fontVariantNumeric",
  "fontVariantPosition",
  "fontVariationSettings",
  "fontWeight",
  "gap",
  "glyphOrientationVertical",
  "grid",
  "gridArea",
  "gridAutoColumns",
  "gridAutoFlow",
  "gridAutoRows",
  "gridColumn",
  "gridColumnEnd",
  "gridColumnGap",
  "gridColumnStart",
  "gridGap",
  "gridRow",
  "gridRowEnd",
  "gridRowGap",
  "gridRowStart",
  "gridTemplate",
  "gridTemplateAreas",
  "gridTemplateColumns",
  "gridTemplateRows",
  "hangingPunctuation",
  "height",
  "hyphens",
  "imageOrientation",
  "imageRendering",
  "imageResolution",
  "imeMode",
  "initialLetter",
  "inlineSize",
  "inset",
  "insetBlock",
  "insetBlockEnd",
  "insetBlockStart",
  "insetInline",
  "insetInlineEnd",
  "insetInlineStart",
  "isolation",
  "justifyContent",
  "justifyItems",
  "justifySelf",
  "left",
  "letterSpacing",
  "lightingColor",
  "lineBreak",
  "lineClamp",
  "lineHeight",
  "lineHeightStep",
  "listStyle",
  "listStyleImage",
  "listStylePosition",
  "listStyleType",
  "margin",
  "marginBlock",
  "marginBlockEnd",
  "marginBlockStart",
  "marginBottom",
  "marginInline",
  "marginInlineEnd",
  "marginInlineStart",
  "marginLeft",
  "marginRight",
  "marginTop",
  "marker",
  "markerEnd",
  "markerMid",
  "markerStart",
  "mask",
  "maskBorder",
  "maskBorderMode",
  "maskBorderOutset",
  "maskBorderRepeat",
  "maskBorderSlice",
  "maskBorderSource",
  "maskBorderWidth",
  "maskClip",
  "maskComposite",
  "maskImage",
  "maskMode",
  "maskOrigin",
  "maskPosition",
  "maskRepeat",
  "maskSize",
  "maskType",
  "maxBlockSize",
  "maxHeight",
  "maxInlineSize",
  "maxLines",
  "maxWidth",
  "minBlockSize",
  "minHeight",
  "minInlineSize",
  "minWidth",
  "mixBlendMode",
  "motion",
  "motionDistance",
  "motionPath",
  "motionRotation",
  "objectFit",
  "objectPosition",
  "offset",
  "offsetAnchor",
  "offsetBlock",
  "offsetBlockEnd",
  "offsetBlockStart",
  "offsetDistance",
  "offsetInline",
  "offsetInlineEnd",
  "offsetInlineStart",
  "offsetPath",
  "offsetRotate",
  "offsetRotation",
  "opacity",
  "order",
  "orphans",
  "outline",
  "outlineColor",
  "outlineOffset",
  "outlineStyle",
  "outlineWidth",
  "overflow",
  "overflowAnchor",
  "overflowBlock",
  "overflowClipBox",
  "overflowInline",
  "overflowWrap",
  "overflowX",
  "overflowY",
  "overscrollBehavior",
  "overscrollBehaviorX",
  "overscrollBehaviorY",
  "padding",
  "paddingBlock",
  "paddingBlockEnd",
  "paddingBlockStart",
  "paddingBottom",
  "paddingInline",
  "paddingInlineEnd",
  "paddingInlineStart",
  "paddingLeft",
  "paddingRight",
  "paddingTop",
  "pageBreakAfter",
  "pageBreakBefore",
  "pageBreakInside",
  "paintOrder",
  "perspective",
  "perspectiveOrigin",
  "placeContent",
  "placeItems",
  "placeSelf",
  "pointerEvents",
  "position",
  "quotes",
  "resize",
  "right",
  "rotate",
  "rowGap",
  "rubyAlign",
  "rubyMerge",
  "rubyPosition",
  "scale",
  "scrollBehavior",
  "scrollMargin",
  "scrollMarginBlock",
  "scrollMarginBlockEnd",
  "scrollMarginBlockStart",
  "scrollMarginBottom",
  "scrollMarginInline",
  "scrollMarginInlineEnd",
  "scrollMarginInlineStart",
  "scrollMarginLeft",
  "scrollMarginRight",
  "scrollMarginTop",
  "scrollPadding",
  "scrollPaddingBlock",
  "scrollPaddingBlockEnd",
  "scrollPaddingBlockStart",
  "scrollPaddingBottom",
  "scrollPaddingInline",
  "scrollPaddingInlineEnd",
  "scrollPaddingInlineStart",
  "scrollPaddingLeft",
  "scrollPaddingRight",
  "scrollPaddingTop",
  "scrollSnapAlign",
  "scrollSnapCoordinate",
  "scrollSnapDestination",
  "scrollSnapPointsX",
  "scrollSnapPointsY",
  "scrollSnapStop",
  "scrollSnapType",
  "scrollSnapTypeX",
  "scrollSnapTypeY",
  "scrollbarColor",
  "scrollbarWidth",
  "shapeImageThreshold",
  "shapeMargin",
  "shapeOutside",
  "shapeRendering",
  "stopColor",
  "stopOpacity",
  "stroke",
  "strokeDasharray",
  "strokeDashoffset",
  "strokeLinecap",
  "strokeLinejoin",
  "strokeMiterlimit",
  "strokeOpacity",
  "strokeWidth",
  "tabSize",
  "tableLayout",
  "textAlign",
  "textAlignLast",
  "textAnchor",
  "textCombineHorizontal",
  "textCombineUpright",
  "textDecoration",
  "textDecorationColor",
  "textDecorationLine",
  "textDecorationSkip",
  "textDecorationSkipInk",
  "textDecorationStyle",
  "textDecorationThickness",
  "textDecorationWidth",
  "textEmphasis",
  "textEmphasisColor",
  "textEmphasisPosition",
  "textEmphasisStyle",
  "textIndent",
  "textJustify",
  "text",
  "textOverflow",
  "textRendering",
  "textShadow",
  "textSizeAdjust",
  "textTransform",
  "textUnderlineOffset",
  "textUnderlinePosition",
  "top",
  "touchAction",
  "transform",
  "transformBox",
  "transformOrigin",
  "transformStyle",
  "transition",
  "transitionDelay",
  "transitionDuration",
  "transitionProperty",
  "transitionTimingFunction",
  "translate",
  "unicodeBidi",
  "userSelect",
  "vectorEffect",
  "verticalAlign",
  "visibility",
  "whiteSpace",
  "widows",
  "width",
  "willChange",
  "wordBreak",
  "wordSpacing",
  "wordWrap",
  "writingMode",
  "zIndex",
  "zoom",
];
